version: '3.8'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT:-5173}:${PORT:-5173}"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - PORT=${PORT:-5173}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev:docker

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-80}:80"
    environment:
      - NODE_ENV=production
    command: ["nginx", "-g", "daemon off;"]

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run test
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
