# Usa la imagen base oficial de devcontainers para Node.js y TypeScript
FROM mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm

# Instala paquetes adicionales si los necesitas
# RUN apt-get update && apt-get install -y <paquete>

# Copia archivos de configuración si es necesario
# COPY .npmrc /root/.npmrc

# Establece el directorio de trabajo
WORKDIR /workspaces/frontend-template