# Dockerfile para entorno de desarrollo Node.js
FROM mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm

# Instala dependencias adicionales si es necesario
# RUN apt-get update && apt-get install -y <paquetes-adicionales>

WORKDIR /workspace

# COPY . .
# RUN npm install

CMD ["sleep", "infinity"]
